# -*- coding: utf-8 -*-
"""Fashion_Trend_Radar_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZbEYcSNjuSCkGDafE4rKBsk5Ak9IiFc
"""

import zipfile

zip_path = 'archive (7).zip'  # replace with your EXACT filename, including spaces/parentheses if present

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('reviews_data')

print("Extraction complete!")

import os
print(os.listdir('reviews_data'))

import pandas as pd

reviews = pd.read_csv('reviews_data/Womens Clothing E-Commerce Reviews.csv')
reviews.head()

# Drop the unnecessary index column, check for missing values
reviews = reviews.drop(columns=['Unnamed: 0'])
print("Missing values:\n", reviews.isnull().sum())

# Remove rows where Review Text is missing (can't analyze sentiment without text)
reviews_clean = reviews.dropna(subset=['Review Text'])
reviews_clean = reviews_clean.copy()

print("Original rows:", len(reviews))
print("Rows after removing missing reviews:", len(reviews_clean))

!pip install textblob
from textblob import TextBlob

sample_review = reviews_clean['Review Text'].iloc[0]
print("Review:", sample_review)

blob = TextBlob(sample_review)
print("Sentiment polarity:", blob.sentiment.polarity)

reviews_clean['sentiment_polarity'] = reviews_clean['Review Text'].apply(lambda x: TextBlob(x).sentiment.polarity)

reviews_clean[['Review Text', 'Rating', 'sentiment_polarity']].head()

avg_sentiment_by_dept = reviews_clean.groupby('Department Name')['sentiment_polarity'].mean().sort_values(ascending=False)
print(avg_sentiment_by_dept)

trend_reviews = reviews_clean[reviews_clean['Department Name'] == 'Trend']
negative_trend_reviews = trend_reviews[trend_reviews['sentiment_polarity'] < 0]

print("Number of negative Trend reviews:", len(negative_trend_reviews))
print(negative_trend_reviews['Review Text'].head(5).tolist())

"""## Sentiment Analysis — Key Finding

Average sentiment across departments is fairly consistent (0.24-0.25) except for
the "Trend" category, which scores notably lower (0.20). Examining negative Trend
reviews directly reveals the core driver isn't values/ethics concerns as originally
hypothesized, but fit inconsistency and fabric/quality gaps between product
expectations and reality ("looks cute in the picture, but not good in person").

**Revised business insight:** Brands prioritizing trend velocity over quality
control risk a specific, measurable trust erosion — customers describe garment
quality and fit failures, not values misalignment, as their primary complaint
in trend-driven pieces.
"""