# -*- coding: utf-8 -*-
"""Fashion_Trend_Radar_DataCollection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNfOncOit35NhgJ5q0mj95Ah84ZfPESw
"""

# Step 1: Install libraries we need
!pip install pytrends praw pandas

import time
from pytrends.request import TrendReq

pytrends = TrendReq(hl='en-US', tz=330)

keywords = ["quiet luxury", "cottagecore", "clean girl aesthetic", "cruelty free skincare"]

time.sleep(5)  # small safety pause before first request
pytrends.build_payload(keywords, timeframe='today 3-m', geo='')

trend_data = pytrends.interest_over_time()
trend_data.head()

# Step 2b: Compare India vs US trends side-by-side
import pandas as pd
import time

# Pull US data
pytrends.build_payload(keywords, timeframe='today 3-m', geo='US')
us_data = pytrends.interest_over_time().drop(columns='isPartial')
us_data['market'] = 'US'

time.sleep(2)  # be polite to Google's servers, avoid getting rate-limited

# Pull India data
pytrends.build_payload(keywords, timeframe='today 3-m', geo='IN')
in_data = pytrends.interest_over_time().drop(columns='isPartial')
in_data['market'] = 'India'

# Combine into one table
combined = pd.concat([us_data, in_data])
combined.head()

# Step 2b: Compare India vs US trends side-by-side
import time

# Pull US data
pytrends.build_payload(keywords, timeframe='today 3-m', geo='US')
us_data = pytrends.interest_over_time().drop(columns='isPartial')
us_data['market'] = 'US'

time.sleep(2)  # be polite to Google's servers, avoid getting rate-limited

# Pull India data
pytrends.build_payload(keywords, timeframe='today 3-m', geo='IN')
in_data = pytrends.interest_over_time().drop(columns='isPartial')
in_data['market'] = 'India'

# Combine into one table
combined = pd.concat([us_data, in_data])
combined.head()

combined.tail()   # shows the LAST 5 rows instead of first

import requests

url = "https://www.reddit.com/r/FemaleFashionAdvice/top.json?limit=25"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

response = requests.get(url, headers=headers)

print("Status code:", response.status_code)
print(response.text[:300])

# Step: Separate US and India data for comparison
us_only = combined[combined['market'] == 'US'].drop(columns='market')
india_only = combined[combined['market'] == 'India'].drop(columns='market')

print("US data shape:", us_only.shape)
print("India data shape:", india_only.shape)

for keyword in keywords:
    correlation = us_only[keyword].corr(india_only[keyword])
    print(f"{keyword}:correlation={correlation:.2f}")

# Step: Data cleaning / preprocessing check
print("Missing values in US data:\n", us_only.isnull().sum())
print("\nMissing values in India data:\n", india_only.isnull().sum())

print("\nDuplicate rows in US data:", us_only.duplicated().sum())
print("Duplicate rows in India data:", india_only.duplicated().sum())

# Step: Investigate the duplicate rows in India data
duplicate_rows = india_only[india_only.duplicated(keep=False)]
duplicate_rows.head(10)

"""## Data Quality Check — Findings

- No missing values in either dataset.
- India dataset showed 73/92 "duplicate" rows — investigated and confirmed these
  reflect genuine flat/zero search interest for these keywords in India during
  April 2026, not data errors.
- Decision: retained all rows, since each represents a real calendar day in a
  time series. Removing them would create false gaps in the trend line.
- Insight: near-zero search volume for English-phrase micro-trends in India may
  indicate either delayed trend adoption or a need for localized keyword
  research (regional terms) in future iterations of this analysis.
"""

import matplotlib.pyplot as plt

# Plot US vs India trend for cottagecore (our most interesting finding)
plt.figure(figsize=(10, 5))
plt.plot(us_only.index, us_only['cottagecore'], label='US', color='blue')
plt.plot(india_only.index, india_only['cottagecore'], label='India', color='orange')
plt.title('Cottagecore: US vs India Search Interest Over Time')
plt.xlabel('Date')
plt.ylabel('Search Interest (0-100)')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Plot all 4 keywords: US vs India, side by side in one figure
fig, axes = plt.subplots(2, 2, figsize=(14, 8))
axes = axes.flatten()

for i, keyword in enumerate(keywords):
    axes[i].plot(us_only.index, us_only[keyword], label='US', color='blue')
    axes[i].plot(india_only.index, india_only[keyword], label='India', color='orange')
    axes[i].set_title(keyword)
    axes[i].legend()
    axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()