# -*- coding: utf-8 -*-
"""Fashion_Trend_Radar_DataCollection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNfOncOit35NhgJ5q0mj95Ah84ZfPESw
"""

# Step 1: Install libraries we need
import time
from pytrends.request import TrendReq

def fetch_with_retry(pytrends_obj, keywords, timeframe, geo, max_attempts=3):
    for attempt in range(max_attempts):
        try:
            pytrends_obj.build_payload(keywords, timeframe=timeframe, geo=geo)
            data = pytrends_obj.interest_over_time()
            print(f"Success on attempt {attempt + 1}")
            return data
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            if attempt < max_attempts - 1:
                wait_time = 90 * (attempt + 1)
                print(f"Waiting {wait_time} seconds before retry...")
                time.sleep(wait_time)
            else:
                print("All retry attempts failed.")
                raise

import time
from pytrends.request import TrendReq

pytrends = TrendReq(hl='en-US', tz=330)

keywords = ["quiet luxury", "cottagecore", "clean girl aesthetic", "cruelty free skincare"]

time.sleep(5)  # small safety pause before first request
trend_data = fetch_with_retry(pytrends, keywords, 'today 3-m', '')


trend_data.head()

# Pull US data
us_data = fetch_with_retry(pytrends, keywords, 'today 3-m', 'US').drop(columns='isPartial')
us_data['market'] = 'US'

time.sleep(5)  # pause between requests

# Pull India data
in_data = fetch_with_retry(pytrends, keywords, 'today 3-m', 'IN').drop(columns='isPartial')
in_data['market'] = 'India'

# Combine into one table
import pandas as pd
combined = pd.concat([us_data, in_data])
combined.head()




combined.tail()   # shows the LAST 5 rows instead of first



# Step: Separate US and India data for comparison
us_only = combined[combined['market'] == 'US'].drop(columns='market')
india_only = combined[combined['market'] == 'India'].drop(columns='market')

print("US data shape:", us_only.shape)
print("India data shape:", india_only.shape)

for keyword in keywords:
    correlation = us_only[keyword].corr(india_only[keyword])
    print(f"{keyword}:correlation={correlation:.2f}")

# Step: Data cleaning / preprocessing check
print("Missing values in US data:\n", us_only.isnull().sum())
print("\nMissing values in India data:\n", india_only.isnull().sum())

print("\nDuplicate rows in US data:", us_only.duplicated().sum())
print("Duplicate rows in India data:", india_only.duplicated().sum())

# Step: Investigate the duplicate rows in India data
duplicate_rows = india_only[india_only.duplicated(keep=False)]
duplicate_rows.head(10)

"""## Data Quality Check — Findings

- No missing values in either dataset.
- India dataset showed 73/92 "duplicate" rows — investigated and confirmed these
  reflect genuine flat/zero search interest for these keywords in India during
  April 2026, not data errors.
- Decision: retained all rows, since each represents a real calendar day in a
  time series. Removing them would create false gaps in the trend line.
- Insight: near-zero search volume for English-phrase micro-trends in India may
  indicate either delayed trend adoption or a need for localized keyword
  research (regional terms) in future iterations of this analysis.
"""

import matplotlib.pyplot as plt

# Plot US vs India trend for cottagecore (our most interesting finding)
plt.figure(figsize=(10, 5))
plt.plot(us_only.index, us_only['cottagecore'], label='US', color='blue')
plt.plot(india_only.index, india_only['cottagecore'], label='India', color='orange')
plt.title('Cottagecore: US vs India Search Interest Over Time')
plt.xlabel('Date')
plt.ylabel('Search Interest (0-100)')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Plot all 4 keywords: US vs India, side by side in one figure
fig, axes = plt.subplots(2, 2, figsize=(14, 8))
axes = axes.flatten()

for i, keyword in enumerate(keywords):
    axes[i].plot(us_only.index, us_only[keyword], label='US', color='blue')
    axes[i].plot(india_only.index, india_only[keyword], label='India', color='orange')
    axes[i].set_title(keyword)
    axes[i].legend()
    axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# Save the final combined data so GitHub Actions can commit it
combined.to_csv('trend_data_latest.csv')
print("Data saved to trend_data_latest.csv")
